services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: online-course
    ports:
      - '4000:4000'
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DATABASE: online_course_database
      PORT: 4000
      MODE: DEV
      RUN_MIGRATIONS: true
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: online_course_database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - '5432:5432'

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
